// Generated by CoffeeScript 1.6.3
var ReactCompiler, transform;

transform = require('react-tools').transform;

module.exports = ReactCompiler = (function() {
  ReactCompiler.prototype.brunchPlugin = true;

  ReactCompiler.prototype.type = 'javascript';

  ReactCompiler.prototype.extension = 'jsx';

  function ReactCompiler(config) {
    var _ref, _ref1, _ref2;
    this.config = config;
    this.includeHeader = ((_ref = this.config) != null ? (_ref1 = _ref.plugins) != null ? (_ref2 = _ref1.react) != null ? _ref2.autoIncludeCommentBlock : void 0 : void 0 : void 0) === true;
  }

  ReactCompiler.prototype.compile = function(params, callback) {
    var err, output, source;
    source = params.data;
    if (this.includeHeader) {
      source = "/** @jsx React.DOM */\n" + source;
    }
    try {
      output = transform(source);
    } catch (_error) {
      err = _error;
      return callback(err.toString());
    }
    return callback(null, {
      data: output
    });
  };

  return ReactCompiler;

})();
