// Generated by CoffeeScript 1.6.3
var ReactCompiler, transform;

transform = require('react-tools').transform;

module.exports = ReactCompiler = (function() {
  ReactCompiler.prototype.brunchPlugin = true;

  ReactCompiler.prototype.type = 'javascript';

  ReactCompiler.prototype.extension = 'jsx';

  function ReactCompiler(config) {
    this.config = config;
    null;
  }

  ReactCompiler.prototype.compile = function(params, callback) {
    var source;
    source = transform(params.data);
    return callback(null, {
      data: source
    });
  };

  return ReactCompiler;

})();
